services:
  - type: web
    name: Music-Audjust
    runtime: python
    pythonVersion: "3.12.0"
    buildCommand: "apt-get install -y ffmpeg && pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
